# Generated by Django 3.1.5 on 2021-01-12 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20201123_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHypothethis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.IntegerField(null=True)),
                ('risk_free_rate', models.IntegerField(null=True)),
                ('broker_fees', models.IntegerField(null=True)),
                ('gamma', models.IntegerField(null=True)),
                ('short_selling', models.BooleanField(null=True)),
                ('allocation', models.CharField(max_length=200)),
                ('tickers_selected', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('strategy', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
