# Generated by Django 3.1.5 on 2021-01-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_recordhypothethis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordHypothethis',
            new_name='RecordHypothesis',
        ),
    ]
