# Generated by Django 3.1.5 on 2021-01-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_auto_20210118_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchicalriskparity',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hropt', to=settings.AUTH_USER_MODEL),
        ),
    ]
