# Generated by Django 3.1.6 on 2021-02-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_auto_20210205_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticallinealgorithm',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='criticallinealgorithm',
            name='risk_model',
        ),
        migrations.RemoveField(
            model_name='criticallinealgorithm',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='efficientfrontier',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='efficientfrontier',
            name='risk_model',
        ),
        migrations.RemoveField(
            model_name='efficientfrontier',
            name='strategy',
        ),
        migrations.RenameField(
            model_name='hierarchicalriskparity',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='hierarchicalriskparity',
            name='strategy',
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='broker_fees',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='capital',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='expected_return',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strategy.expectedreturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='gamma',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='risk_free_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='short_selling',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalriskparity',
            name='tickers_selected',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordhypothesis',
            name='expected_return',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recordhypothesis',
            name='risk',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='BlackLitterman',
        ),
        migrations.DeleteModel(
            name='CriticalLineAlgorithm',
        ),
        migrations.DeleteModel(
            name='EfficientFrontier',
        ),
    ]
