# Generated by Django 3.1.6 on 2021-02-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_auto_20210205_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordhypothesis',
            old_name='user_id',
            new_name='user',
        ),
    ]
