# Generated by Django 3.1.7 on 2021-03-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_historicalvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvalue',
            name='expected_return',
        ),
    ]
