# Generated by Django 3.1.7 on 2021-03-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_remove_historicalvalue_expected_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvalue',
            name='risk_model',
        ),
    ]
