# Generated by Django 3.1.7 on 2021-03-25 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0012_remove_historicalvalue_risk_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvalue',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='historicalvalue', to='auth.user'),
            preserve_default=False,
        ),
    ]
