# Generated by Django 4.0.3 on 2022-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0014_auto_20210325_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhypothesis',
            name='allocation',
            field=models.JSONField(),
        ),
    ]
