# Generated by Django 3.1.3 on 2020-11-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.IntegerField(null=True)),
                ('industry', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.IntegerField(null=True)),
                ('high_price', models.IntegerField(null=True)),
                ('low_price', models.IntegerField(null=True)),
                ('close_price', models.IntegerField(null=True)),
                ('adj_close_price', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('price_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('data_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnal.datavendor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnal.coin')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnal.exchange'),
        ),
    ]
