# Generated by Django 3.1.7 on 2021-03-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_historicalvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_hypothesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpreferredhypothesis', to='strategy.recordhypothesis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermeta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
